"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "../../providers";
import { ToastContainer } from "react-toastify";
import { Toaster } from "react-hot-toast";
import { RecoilRoot } from "recoil";
import "../styles/app.css"


const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <RecoilRoot>
          <Providers>
            {children}
            <div id="portal"></div>
            <Toaster />
            <ToastContainer />
          </Providers>
        </RecoilRoot>

      </body>
    </html>
  );
}
